soft.pkgs <- c("AnnotationHub", 
               "BSgenome", 
               "Biobase", 
               "Biostrings", 
               "GEOquery", 
               "GenomeInfoDb", 
               "GenomicFeatures", 
               "GenomicRanges", 
               "IRanges", 
               "Rsamtools",
               "ShortRead",
               "biomaRt",
               "minfi",
               "oligo",
               "rtracklayer")

data.pkgs <- c("ALL",
               "BSgenome.Hsapiens.UCSC.hg19",
               "BSgenome.Scerevisiae.UCSC.sacCer2",
               "TxDb.Hsapiens.UCSC.hg19.knownGene",
               "airway",
               "hgu95av2.db",
               "leeBamViews",
               "leukemiasEset",
               "minfiData",
               "yeastRNASeq",
               "zebrafishRNASeq")

