---
title: "RNA-seq analysis with DESeq2 and edgeR"
author: "Kasper D. Hansen"
bibliography: genbioconductor.bib
---

```{r front, child="front.Rmd", echo=FALSE}
```

## Dependencies

This document has the following dependencies:

```{r dependencies, warning=FALSE, message=FALSE}
library(DESeq)
library(edgeR)
```

Use the following commands to install these packages in R.

```{r biocLite, eval=FALSE}
source("http://www.bioconductor.org/biocLite.R")
biocLite(c("DESeq", "edgeR))
```

## Overview
  
Blah

## Other Resources

- The vignette from the [edgeR webpage](http://bioconductor.org/packages/edgeR).
- The vignette from the [DESeq webpage](http://bioconductor.org/packages/DESeq).

## RNA-seq count data

## edgeR

```{r}
library(airway)
data(airway)
airway
assay(airway, "counts")[1:3, 1:3]
airway$dex
```

```{r}
library(DESeq2)
se <- airway
se$dex
se$dex <- relevel(se$dex, "untrt")
dds <- DESeqDataSet(se, design = ~ dex)
dds <- DESeq(dds)
res <- results(dds)
res <- res[order(res$padj),]
```

```{r}
library(edgeR)
dge <- DGEList(counts = assay(se, "counts"),
               group = se$dex)
dge$samples <- merge(dge$samples,
                     as.data.frame(colData(se)),
                     by = 0)
dge$genes <- data.frame(name = names(rowRanges(se)),
                        stringsAsFactors = FALSE)
dge <- calcNormFactors(dge)

design <- model.matrix(~dge$samples$group)
dge <- estimateGLMCommonDisp(dge)
dge <- estimateGLMTagwiseDisp(dge)
fit <- glmFit(dge, design)
lrt <- glmLRT(fit, coef = 2)
topTags(lrt)
```


## DESeq


## SessionInfo

\scriptsize

```{r sessionInfo, echo=FALSE}
sessionInfo()
```

## References
